config/routes.rb
Rails.application.routes.draw do
  mount API => "/"
  devise_for :users
  resources :users
  resources :notes
  resources :courses
  get "/add" => "notes#index"
  root 'home#index'

end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :notes
end

app/models/note.rb
class Note < ActiveRecord::Base
  validates :topic, presence: true, length: { minimum: 10 }
  validates :description, presence: true, length: { maximum: 500 }
  belongs_to :user
  belongs_to :course

  def initialize(params={})
    file = params.delete(:file)
    super
    if file
      self.filename = sanitize_filename(file.original_filename)
      self.content_type = file.content_type
      self.file_contents = file.read
    end
  end
  def content
    if self.content_type.split("/")[0] == "text"
      self.file_contents 
    else
      "can not display in text"
    end
  end
  private
    def sanitize_filename(filename)
      return File.basename(filename)
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @notes = Note.all
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  def index
    @notes = Note.all
  end


  def show
    # send the binary data to the browser
    send_data(@note.file_contents, type: @note.content_type, filename: @note.filename)
  end

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(note_params)

    if @note.save
      redirect_to notes_path
    else
      render 'new'
    end
  end

  def update
    if @note.update(note_params)
      redirect_to @note
    else
      render 'edit'
    end
  end

  def destroy
    @note.destroy
    redirect_to notes_url
  end

  private
    def set_note
      @note = Note.find(params[:id])
    end

    def note_params
      params.require(:note).permit(:file, :topic, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/home/index.html.erb
<%= stylesheet_link_tag    'home', media: 'all', 'data-turbolinks-track' => true %>

<h1>AirLeaf</h1>
<p>Our Homepage</p>
<div class="function-area">
  <div class="search-container">
    <form>
      <label>search the Note here!</label>
      <input type="text"/>
      <input type="submit" value="search"/>
    </form>
  </div>
  <div class="add-note-container">
    <p class="add-note-text"> add your note </p>
    <%= image_tag("pluss-sign.gif", class: "pluss-sign") %> 
  </div> 
</div>
<hr>
<div class="content-area">
  <div class="note-list">
  <p> popular note </p>
    <ul class="list-group">
    <% @notes.each do |note| %>
     <li class="list-group-item">
       <span class="badge"></span>
       <%= note.topic %>
     </li>
    <% end%>
   </ul> 
  </div>
<div class="note-content panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Panel title</h3>
  </div>
  <div class="panel-body">
    Basic panel example  something load from note
  </div>
</div>

</div>


<div id="dialog-form" title="Create new Note">
  <p class="validateTips">All form fields are required.</p>
 
  <form>
    <fieldset>
      <label for="topic">Topic</label>
      <input type="text" name="topic" id="topic" value="" class="text ui-widget-content ui-corner-all">
      <label for="course">Course</label>
      <input type="text" name="course" id="course" value="" class="text ui-widget-content ui-corner-all">
      <label for="description">Description</label>
      <input type="text" name="description" id="description" value="" class="text ui-widget-content ui-corner-all">
      <label for="note">Note</label>
      <input type="file" name="file" id="file" value="" class="text ui-widget-content ui-corner-all">
 
      <!-- Allow form submission with keyboard without duplicating the dialog button -->
      <input type="submit" tabindex="-1" style="position:absolute; top:-1000px">
    </fieldset>
  </form>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AirLeaf</title>
  <!-- Latest compiled and minified CSS -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
<nav class="navbar navbar-default">
  <div class="container-fluid">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Home</a>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">MyNotes <span class="sr-only">(current)</span></a></li>
        <li><a href="#">About</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Help</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

  </header>
  <%= yield %>
  <footer>
  </footer>
</body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>

  <div class="field">
    <%= f.file_field :file %>

    <%= f.label :topic %>
    <%= f.text_field :topic %>

    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div><%= f.submit %></div>
<% end %>

app/views/notes/index.html.erb
<h2>Listing notes</h2>

<div>
  <p>Filename</p>
  <div>
    <% @notes.each do |note| %>
      <ul>
        <li>
          <%= note.filename %>
          <%= button_to 'Download', note, method: :get %>
          <%= button_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %>
        </li>
      </ul>
    <% end %>
  </div>
</div>

<br>

<%= link_to 'New Document', new_note_path %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>